### ISSUE TITLE
404_override issue

### ISSUE THREAD

**Issue by inverse** [katzgrau/getsparks.org#17]
I don't know if this is a problem directly with sparks. 

 I have a 404_override that points to a controller/method that uses the assets spark:

```
  $route['404_override'] = 'errors/error404';
```

This works fine except in one condition, when the controller exists, but the method doesn't e.g.

myurl.com/exists/fhfjkhfjklf

It would appear in such cases the sparks are not getting loaded correctly? You can simulate this easily by calling the example spark in such instance and seeing the error regarding undefined function.

```
   Fatal error: Call to a member function printHello() 
```

I hope this makes sense.

**Comment by unek** [comment]
Same happens for me. Any solution yet?
