### ISSUE TITLE
search vs. spec API

### ISSUE THREAD

**Issue by bschaeffer** [katzgrau/getsparks.org#3]
Why do `/api/packages/search/` and `/api/packages/spec/...` return different sets of data? For instance the **search** API does not return `archive_url`, `is_deactivated` or `contributor` (etc...). The resulting data is a reduced set, but doesn't feel small enough to warrant omitting stuff like that. 

Personally, I think the resulting spark data from both API calls should be identical, but I was just wondering if there was a reason behind this... Thanks!

**Comment by katzgrau** [comment]
The real reason behind it is that the functionality was written at separate times in two different function calls. As the spark manager was being written, @seejohnrun would ask for different attributes that he needed back, and they were added ad-hoc. The don't match up exactly with the search api, but making them match wouldn't be difficult either.
